Commands tests
AY2021S1-CS2103-F10-3/tp pull request #62
Opened 2020-10-12 10:58 UTC by youaremysky99

- All the tests passed

- Check-style okay.

2020-10-12 16:37 UTC, Jillzyt commented on src/test/java/seedu/fma/logic/commands/AddCommandIntegrationTest.java
> +    public void execute_newPerson_success() {
Method name not refactored to Log

2020-10-12 16:38 UTC, Jillzyt commented on src/test/java/seedu/fma/logic/commands/AddCommandIntegrationTest.java
> +    public void execute_duplicatePerson_throwsCommandException() {
Method name not refactored to Log

2020-10-12 16:47 UTC, Jillzyt commented on src/test/java/seedu/fma/logic/commands/FindCommandTest.java
> +    public void execute_multipleKeywords_multiplePersonsFound() {
Person not refactored to Log

2020-10-12 16:50 UTC, Jillzyt requested changes
LGTM 👍  Is the few instances of person left intentionally?

2020-10-13 02:38 UTC, jeminsieow commented
Remember to pull and fix the merge conflicts

2020-10-13 04:19 UTC, Jillzyt commented
LGTM.

2020-10-13 04:20 UTC, Jillzyt approved these changes

2020-10-13 04:20 UTC, merged